name: gameap

services:
  gameap:
    image: gameap/gameap:latest
    container_name: gameap
    restart: always
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER_NAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "80:8000"
    env_file: .env

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    env_file: .env